version: "3.8"
services:

    nginx:
        restart: always
        image: nginx:latest
        container_name: nginx
        volumes:
            - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - "8080:80"

#    db:
#        image: mysql
#        # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
#        # (this is just an example, not intended to be a production configuration)
#        command: --default-authentication-plugin=mysql_native_password
#        restart: always
#        container_name: user-db
#        environment:
#            MYSQL_ROOT_PASSWORD: example

    user-db:
        command: --init-file /tmp/create-db.sql
        build:
            context: ./user-db
        ports:
            - "3306:3306"
        container_name: user-db
        environment:
            MYSQL_ROOT_PASSWORD: password

    product-db:
        command: --init-file /tmp/create-db.sql
        build:
            context: ./product-db
        ports:
            - "3307:3307"
        container_name: product-db
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_TCP_PORT: 3307


    users:
        build:
            context: ./users
        ports:
            - "3002:3002"
        container_name: users
        depends_on:
            - nginx
            - user-db
        environment:
            MYSQL_DATABASE: local_db
            MYSQL_USER: root
            MYSQL_PASSWORD: password
            MYSQL_HOST: user-db


    products:
        build:
            context: ./products
        ports:
            - "3001:3001"
        container_name: products
        depends_on:
            - nginx
            - product-db
        environment:
            MYSQL_DATABASE: local_db
            MYSQL_USER: root
            MYSQL_PASSWORD: password
            MYSQL_HOST: product-db