version: "3.8"
services:

    nginx:
        restart: always
        image: nginx:latest
        container_name: nginx
        volumes:
            - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - "8080:80"

    user-db:
        command: --init-file /tmp/create-db.sql
        build:
            context: ./user-db
        ports:
            - "3306:3306"
        container_name: user-db
        environment:
            MYSQL_ROOT_PASSWORD: password

    product-db:
        command: --init-file /tmp/create-db.sql
        build:
            context: ./product-db
        ports:
            - "3307:3307"
        container_name: product-db
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_TCP_PORT: 3307


    users:
        build:
            context: ./users
        ports:
            - "3002:3002"
        container_name: users
        depends_on:
            - nginx
            - user-db
        environment:
            MYSQL_DATABASE: local_db
            MYSQL_USER: root
            MYSQL_PASSWORD: password
            MYSQL_HOST: user-db


    products:
        build:
            context: ./products
        ports:
            - "3001:3001"
        container_name: products
        depends_on:
            - nginx
            - product-db
        environment:
            MYSQL_DATABASE: local_db
            MYSQL_USER: root
            MYSQL_PASSWORD: password
            MYSQL_HOST: product-db

    client:
        image: client
        build:
            context: ./client
            dockerfile: Dockerfile 
        volumes:
            - ./client:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
        ports:
            - 3000:3000
        container_name: client
