kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv-volume-user
  labels:
    type: local
spec:
  storageClassName: cinder-high-speed # CHANGE HERE
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/data_user"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim-user
spec:
  storageClassName: cinder-high-speed # CHANGE HERE
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
