apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: node
          image: simonlechner/product
          env:
          - name: MYSQL_HOST
            value: mysql-product
          - name: MYSQL_USER
            value: "root"
          - name: MYSQL_PASSWORD
            value: "password"
          - name: MYSQL_DATABASE
            value: "local_db"
          ports:
            - containerPort: 3307
---
apiVersion: v1
kind: Service
metadata:
  name: node
spec:
  type: NodePort 
  selector:
    app: node
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
    nodePort: 30101
